### PR TITLE
Added converter support for booleans

### PR DESCRIPTION
**Pull request by mikesir87**
Looks like it was simply forgotten. Feel free to move it elsewhere since I know this branch is still in flux.

### CODE REVIEW

**Comment by ceharris** [comment]
Booleans are handled at a lower layer -- see AbstractViewWriter -- but it is missing boolean primitives. It's fixed in the soon to be merged model editor branch, but could be easily fixed on master.

carl

**Comment by ceharris** [comment]
Actually, it's in JsonViewWriter and it should be working on master.

**Comment by mikesir87** [comment]
Ok. I was taking a sneak peek at the model-editor branch and was hit with
the "unable to coerce" exception when trying to read a view with a boolean
value.  Note that that was reading, not writing the view.  But, I recognize
you most likely have local changes that haven't been pushed.  So, figured
I'd just let you know in case you hadn't included booleans in your tests.

--
Michael

**Comment by ceharris** [comment]
That's what I get for trying to review pull requests at the softball field.  :-)

**Pull request closed without merging**
